heat_template_version: 2015-04-30

description: DP_HA-dpmediation

parameters:
  lvsrouter_internal_ip_list: 
    type: string

  enm_rhel6_jboss_image_name:
    type: string

  enm_internal_network_name:
    type: string

  internal_port_security_enabled:
    type: boolean

  nat_combined_security_groups:
    type: comma_delimited_list
    description: "Not SED KEY"
    default: "frstaging01_internal_security_group,frstaging01_external_security_group"

  enm_external_security_group_name:
    type: string

  allowed_address_pairs:
    type: comma_delimited_list
    description: "Not SED KEY"
    default: "0.0.0.0/0,::/0"

  flavor_dpmediation:
    type: string

  key_name:
    type: string

  use_config_drive:
    type: boolean
    default: true

  internal_netmask:
    type: string

  svc_CM_vip_internal:
    type: string

  service_registry_dns_port:
    type: string
    default: 8600

  service_registry_datacenter:
    type: string
    default: dc1

  service_registry_domain:
    type: string
    default: enm

  serviceregistry_internal_ip_list:
    type: comma_delimited_list

  server_group_policy:
    type: comma_delimited_list

  timezone:
    type: string

  enm_external_network_name:
    type: string

  external_gateway_ipv6:
    type: string
    default: ''

  external_mtu:
    type: string
    default: 1500

  dpmediation_instances:
    type: string
    default: 2

  dpmediation_internal_ip_list:
    type: comma_delimited_list

  dpmediation_external_ipv6_list:
    type: comma_delimited_list
    default: ['', '']

  deployment_id:
    type: string

  ha_policy:
    type: string

  tags:
    type: json
    description: "Not SED KEY"
    default: {"enm_deployment_id": "stg01", "enm_stack_name": "DP_HA_dpmediation"}

  svc_CM_vip_external_ipv6_address:
    type: string
    default: ""

  svc_FM_vip_external_ipv6_address:
    type: string
    default: ""

  svc_PM_vip_external_ipv6_address:
    type: string
    default: ""

resources:
  dpmediation_server_group:
    type: OS::Nova::ServerGroup
    properties:
      name: dpmediation_server_group
      policies: {get_param: server_group_policy}

  dpmediation:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: dpmediation_instances}
      resource_def:
        type: dpmediation_definition.yaml
        properties:
          NodeIndex: '%index%'
          deployment_id: {get_param: deployment_id}
          ha_policy: {get_param: ha_policy}
          dpmediation_internal_ip_list: {get_param: dpmediation_internal_ip_list}
          dpmediation_external_ipv6_list: {get_param: dpmediation_external_ipv6_list}
          enm_rhel6_jboss_image_name: {get_param: enm_rhel6_jboss_image_name}
          enm_internal_network_name: {get_param: enm_internal_network_name}
          nat_combined_security_groups: {get_param: nat_combined_security_groups}
          internal_port_security_enabled: {get_param: internal_port_security_enabled}
          allowed_address_pairs: {get_param: allowed_address_pairs}
          enm_external_security_group_name: {get_param: enm_external_security_group_name}
          flavor_dpmediation: {get_param: flavor_dpmediation}
          key_name: {get_param: key_name}
          use_config_drive: {get_param: use_config_drive}
          serviceregistry_internal_ip_list: {get_param: serviceregistry_internal_ip_list}
          server_group_uuid: {get_resource: dpmediation_server_group}
          internal_netmask: {get_param: internal_netmask}
          svc_CM_vip_internal: {get_param: svc_CM_vip_internal}
          service_registry_dns_port: {get_param: service_registry_dns_port}
          service_registry_datacenter: {get_param: service_registry_datacenter}
          service_registry_domain: {get_param: service_registry_domain}
          timezone: {get_param: timezone}
          enm_external_network_name: {get_param: enm_external_network_name}
          external_gateway_ipv6: {get_param: external_gateway_ipv6}
          external_mtu: {get_param: external_mtu}
          svc_CM_vip_external_ipv6_address: {get_param: svc_CM_vip_external_ipv6_address}
          svc_FM_vip_external_ipv6_address: {get_param: svc_FM_vip_external_ipv6_address}
          svc_PM_vip_external_ipv6_address: {get_param: svc_PM_vip_external_ipv6_address}
          lvsrouter_internal_ip_list: {get_param: lvsrouter_internal_ip_list}
